name:                thrift-haskell
version:             0.1.0.0
license:             BSD3
author:              "winterland1989"
maintainer:          "winterland1989@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: desc

dependencies:
- base >= 4.7 && < 5
- tcp-streams  >= 1.0
- io-streams
- wire-streams
- network
- containers
- unordered-containers
- monad-loops
- hashable
- text
- bytestring
- binary == 0.8.*
- binary-ieee754
- binary-parsers >= 0.2.1

library:
  source-dirs: src


tests:
  thrift-haskell-spec:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
